### ISSUE TITLE
Group Access panel filter needed

### ISSUE THREAD

**Issue by epatrick** [quandis/qbo3#20]
Design > Group Access has a filter for rows, but not for the Group Access (`ObjectAccess/ListByGroup`) panel. Adding access to any template that has more than 25 rows (like, say, QDM with over 500 task templates) is problematic.

Add a filter field to the UI, and extend `ObjectAccess/ListByGroup` to limit results to only object matching the filter.

**Comment by kcassidyq** [comment]
Filter field has been added.
