### ISSUE TITLE
Message/Send with SMS provider

### ISSUE THREAD

**Issue by epatrick** [quandis/qbo3#23]
QBO3 implements SMS texting via an `IMailOutbound` provider wrapper around Twilio.

The `Message/Send` and `Message/SaveEmail` methods require addresses to be valid emails. This forces users or power users to pass phone numbers as `{Number}@{domain.com}`; e.g. `+18005551212@twilio.com`.

We should consider either:

1. Moving the call email validation out of `Message/Send` and into the `IMailOutbound` providers, or
2. Implement `Message/Text` and `Message/SaveText` methods that validate phone numbers rather than email address.

I'm inclined to go down path 1; thoughts?

**Comment by kcassidyq** [comment]
MailOutboundConfig supports an additional attribute for RegExValidator that corresponds to a RegEx Validator in Expressions.resx.  The default value is "Email".
