### ISSUE TITLE
MailInbound, MailOutbound, and MailProcessor configuration entries

### ISSUE THREAD

**Issue by epatrick** [quandis/qbo3#24]
Extend the subject `ConfigurationElements` in `qbo.Message` to derive from `DbConfigurationElement`, so we can data-drive entries from the `ConfigurationEntry` table.

**Comment by kcassidyq** [comment]
MailInboundCollection was already configured and looks for "Account" nodes.
MailOutboundCollection was already configured and looks for "MailOutbound" nodes.
MailProcessorCollection has been updated and looks for "Processor" nodes.
